// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for pet documents */
interface PetDocumentData {
  /**
   * Slice Zone field in *pet*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: pet.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<PetDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *pet*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: pet.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_description: prismic.KeyTextField;
  /**
   * Meta Image field in *pet*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pet.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>;
  /**
   * Meta Title field in *pet*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: pet.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Slice for *pet → Slice Zone*
 *
 */
type PetDocumentDataSlicesSlice = CarouselMeetSlice;
/**
 * pet document from Prismic
 *
 * - **API ID**: `pet`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PetDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PetDocumentData>, "pet", Lang>;
/** Content for pets documents */
interface PetsDocumentData {
  /**
   * Slice Zone field in *pets*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: pets.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<PetsDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *pets*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: pets.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_description: prismic.KeyTextField;
  /**
   * Meta Image field in *pets*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pets.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>;
  /**
   * Meta Title field in *pets*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: pets.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Slice for *pets → Slice Zone*
 *
 */
type PetsDocumentDataSlicesSlice = never;
/**
 * pets document from Prismic
 *
 * - **API ID**: `pets`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PetsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<PetsDocumentData>, "pets", Lang>;
export type AllDocumentTypes = PetDocument | PetsDocument;
/**
 * Primary content in CarouselMeet → Primary
 *
 */
interface CarouselMeetSliceDefaultPrimary {
  /**
   * name field in *CarouselMeet → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel_meet.primary.name
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  name: prismic.RichTextField;
}
/**
 * Item in CarouselMeet → Items
 *
 */
export interface CarouselMeetSliceDefaultItem {
  /**
   * petImage field in *CarouselMeet → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel_meet.items[].petimage
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  petimage: prismic.ImageField<never>;
}
/**
 * Default variation for CarouselMeet Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CarouselMeetSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CarouselMeetSliceDefaultPrimary>,
  Simplify<CarouselMeetSliceDefaultItem>
>;
/**
 * Slice variation for *CarouselMeet*
 *
 */
type CarouselMeetSliceVariation = CarouselMeetSliceDefault;
/**
 * CarouselMeet Shared Slice
 *
 * - **API ID**: `carousel_meet`
 * - **Description**: `CarouselMeet`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CarouselMeetSlice = prismic.SharedSlice<
  "carousel_meet",
  CarouselMeetSliceVariation
>;
/**
 * Primary content in HeroMeet → Primary
 *
 */
interface HeroMeetSliceDefaultPrimary {
  /**
   * Heading field in *HeroMeet → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_meet.primary.heading
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  heading: prismic.RichTextField;
  /**
   * Description field in *HeroMeet → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_meet.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismic.RichTextField;
}
/**
 * Default variation for HeroMeet Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroMeetSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroMeetSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *HeroMeet*
 *
 */
type HeroMeetSliceVariation = HeroMeetSliceDefault;
/**
 * HeroMeet Shared Slice
 *
 * - **API ID**: `hero_meet`
 * - **Description**: `HeroMeet`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroMeetSlice = prismic.SharedSlice<
  "hero_meet",
  HeroMeetSliceVariation
>;
/**
 * Primary content in NewSlice → Primary
 *
 */
interface NewSliceSliceDefaultPrimary {
  /**
   * Image field in *NewSlice → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: new_slice.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>;
}
/**
 * Default variation for NewSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NewSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewSliceSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *NewSlice*
 *
 */
type NewSliceSliceVariation = NewSliceSliceDefault;
/**
 * NewSlice Shared Slice
 *
 * - **API ID**: `new_slice`
 * - **Description**: `NewSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NewSliceSlice = prismic.SharedSlice<
  "new_slice",
  NewSliceSliceVariation
>;
/**
 * Primary content in TextBlock → Primary
 *
 */
interface TextBlockSliceDefaultPrimary {
  /**
   * title field in *TextBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.RichTextField;
}
/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *TextBlock*
 *
 */
type TextBlockSliceVariation = TextBlockSliceDefault;
/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: `TextBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextBlockSlice = prismic.SharedSlice<
  "text_block",
  TextBlockSliceVariation
>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      PetDocumentData,
      PetDocumentDataSlicesSlice,
      PetDocument,
      PetsDocumentData,
      PetsDocumentDataSlicesSlice,
      PetsDocument,
      AllDocumentTypes,
      CarouselMeetSliceDefaultPrimary,
      CarouselMeetSliceDefaultItem,
      CarouselMeetSliceDefault,
      CarouselMeetSliceVariation,
      CarouselMeetSlice,
      HeroMeetSliceDefaultPrimary,
      HeroMeetSliceDefault,
      HeroMeetSliceVariation,
      HeroMeetSlice,
      NewSliceSliceDefaultPrimary,
      NewSliceSliceDefault,
      NewSliceSliceVariation,
      NewSliceSlice,
      TextBlockSliceDefaultPrimary,
      TextBlockSliceDefault,
      TextBlockSliceVariation,
      TextBlockSlice,
    };
  }
}
