// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice = SlidesHeroOneSlice;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>
  /**
   * Meta Description field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type PetDocumentDataSlicesSlice = CarouselMeetSlice;

/**
 * Content for pet documents
 */
interface PetDocumentData {
  /**
   * Slice Zone field in *pet*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: pet.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PetDocumentDataSlicesSlice>
  /**
   * Meta Description field in *pet*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: pet.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *pet*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pet.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *pet*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: pet.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * pet document from Prismic
 *
 * - **API ID**: `pet`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PetDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PetDocumentData>, "pet", Lang>;

type PetsDocumentDataSlicesSlice = never;

/**
 * Content for pets documents
 */
interface PetsDocumentData {
  /**
   * Slice Zone field in *pets*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: pets.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PetsDocumentDataSlicesSlice>
  /**
   * Meta Description field in *pets*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: pets.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *pets*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pets.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *pets*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: pets.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * pets document from Prismic
 *
 * - **API ID**: `pets`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PetsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<PetsDocumentData>, "pets", Lang>;

export type AllDocumentTypes = HomepageDocument | PetDocument | PetsDocument;

/**
 * Primary content in *CarouselMeet → Primary*
 */
export interface CarouselMeetSliceDefaultPrimary {
  /**
   * name field in *CarouselMeet → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel_meet.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;
}

/**
 * Primary content in *CarouselMeet → Items*
 */
export interface CarouselMeetSliceDefaultItem {
  /**
   * petImage field in *CarouselMeet → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel_meet.items[].petimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  petimage: prismic.ImageField<never>;
}

/**
 * Default variation for CarouselMeet Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselMeetSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CarouselMeetSliceDefaultPrimary>,
  Simplify<CarouselMeetSliceDefaultItem>
>;

/**
 * Slice variation for *CarouselMeet*
 */
type CarouselMeetSliceVariation = CarouselMeetSliceDefault;

/**
 * CarouselMeet Shared Slice
 *
 * - **API ID**: `carousel_meet`
 * - **Description**: CarouselMeet
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselMeetSlice = prismic.SharedSlice<
  "carousel_meet",
  CarouselMeetSliceVariation
>;

/**
 * Primary content in *HeroMeet → Primary*
 */
export interface HeroMeetSliceDefaultPrimary {
  /**
   * Heading field in *HeroMeet → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_meet.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *HeroMeet → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_meet.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for HeroMeet Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroMeetSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroMeetSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroMeet*
 */
type HeroMeetSliceVariation = HeroMeetSliceDefault;

/**
 * HeroMeet Shared Slice
 *
 * - **API ID**: `hero_meet`
 * - **Description**: HeroMeet
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroMeetSlice = prismic.SharedSlice<
  "hero_meet",
  HeroMeetSliceVariation
>;

/**
 * Primary content in *NewSlice → Primary*
 */
export interface NewSliceSliceDefaultPrimary {
  /**
   * Image field in *NewSlice → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: new_slice.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for NewSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NewSlice*
 */
type NewSliceSliceVariation = NewSliceSliceDefault;

/**
 * NewSlice Shared Slice
 *
 * - **API ID**: `new_slice`
 * - **Description**: NewSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewSliceSlice = prismic.SharedSlice<
  "new_slice",
  NewSliceSliceVariation
>;

/**
 * Primary content in *SlidesHeroOne → Items*
 */
export interface SlidesHeroOneSliceDefaultItem {
  /**
   * uid field in *SlidesHeroOne → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slides_hero_one.items[].uid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  uid: prismic.KeyTextField;

  /**
   * title field in *SlidesHeroOne → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: slides_hero_one.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * content field in *SlidesHeroOne → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slides_hero_one.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * image field in *SlidesHeroOne → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slides_hero_one.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * kind field in *SlidesHeroOne → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slides_hero_one.items[].kind
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  kind: prismic.RichTextField;
}

/**
 * Default variation for SlidesHeroOne Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SlidesHeroOneSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<SlidesHeroOneSliceDefaultItem>
>;

/**
 * Slice variation for *SlidesHeroOne*
 */
type SlidesHeroOneSliceVariation = SlidesHeroOneSliceDefault;

/**
 * SlidesHeroOne Shared Slice
 *
 * - **API ID**: `slides_hero_one`
 * - **Description**: SlidesHeroOne
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SlidesHeroOneSlice = prismic.SharedSlice<
  "slides_hero_one",
  SlidesHeroOneSliceVariation
>;

/**
 * Primary content in *TextBlock → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
  /**
   * title field in *TextBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextBlock*
 */
type TextBlockSliceVariation = TextBlockSliceDefault;

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSlice = prismic.SharedSlice<
  "text_block",
  TextBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      PetDocument,
      PetDocumentData,
      PetsDocument,
      PetsDocumentData,
      AllDocumentTypes,
      CarouselMeetSlice,
      CarouselMeetSliceVariation,
      CarouselMeetSliceDefault,
      HeroMeetSlice,
      HeroMeetSliceVariation,
      HeroMeetSliceDefault,
      NewSliceSlice,
      NewSliceSliceVariation,
      NewSliceSliceDefault,
      SlidesHeroOneSlice,
      SlidesHeroOneSliceVariation,
      SlidesHeroOneSliceDefault,
      TextBlockSlice,
      TextBlockSliceVariation,
      TextBlockSliceDefault,
    };
  }
}
