module.exports = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        darkBg: "#151517",
        darkContSecond: "#1E1E1E",
        contAccent: "#0059E0",
        darkContThird: "#7EB0DF",
        contInactive: "#AFAFAF",
      },
      fontFamily: {
        Noto: ["Noto Sans", "sans-serif"],
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        Display: "6rem",
        Display2: "3.75rem",
        Heading1lg: "3rem",
        Heading1sm: "2.125rem",
        Heading2lg: "2.125rem",
        Heading2sm: "1.5rem",
        Heading3lg: "1.5rem",
        Heading3sm: "1.25rem",
        Heading4lg: "1.25rem",
        Heading4sm: "1rem",
        Heading5lg: "1rem",
        Heading5sm: "0.875rem",
        Heading6lg: "0.875rem",
        Heading6sm: "0.75rem",
        Body1lg: "1rem",
        Body1sm: "0.875rem",
        Captionlg: "0.75rem",
        Captionsm: "0.6875rem",
        Footer: "0.625rem",
      },
      fontWeight: {
        black: 900,
        extraBold: 800,
        bold: 700,
        semiBold: 600,
        medium: 500,
        regular: 400,
        light: 300,
        extraLight: 200,
        thin: 100,
      },
    },
  },
};
